#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
let build = 1;

try {
  const { execSync } = require("child_process");
  const count = execSync("git rev-list --count HEAD", {
    encoding: "utf8",
    cwd: root,
  }).trim();
  build = Math.max(1, parseInt(count, 10) || 1);
} catch (e) {
  // no git or error – keep default
}

const outPath = path.join(root, "version.js");
const content = `// Auto-generated by scripts/write-version.js (run before start)\nexport default { build: ${build} };\n`;
fs.writeFileSync(outPath, content);
console.log("Version written: build", build);
